### ISSUE TITLE
Getting NullpointerException while testing

### ISSUE THREAD

**Issue by v71017** [film42/bae#5]
While testing I am getting Null pointer exception in below logic.

// Update likelihood for words not in features
                double likelihood = likelihoodOf.get(label);

label -> negative
likelihoodOf -> {negative=null}

This is throwing nullpointer exception. How to handle this , pls help

**Comment by film42** [comment]
I'm not seeing how it's possible to end up with that result. Are you trying to call into things yourself?

**Comment by v71017** [comment]
Nope, I am just trying to execute the unit test case
 @Test
    public void canCorrectlyClassifyNegativeWithThreeLabels()

**Comment by v71017** [comment]
Hello sir , any update on this issue

**Comment by film42** [comment]
@v71017 you need to call `classifier.calculateInitialLikelihoods();` before attempting to classify. Just opened a PR with a fix.
